"""Numerical and scheduling constants for Mixture-of-Transformer modules."""

SDPA_EXPLICIT_MAX_TOKENS = 4096
SDPA_FALLBACK_CHUNK = 1024
ROUTER_LOGIT_LIMIT = 80.0
ROUTER_Z_LOSS_LIMIT = 80.0
DEFAULT_TEMPERATURE_ANNEAL_FACTOR = 0.97
DEFAULT_MIN_TEMPERATURE = 0.3
