"""Numerical and scheduling constants for Mixture-of-Attention modules."""

DEFAULT_RF_SEED = 0x5F3759DF
LINEAR_ATTN_THRESHOLD = 512
LINEAR_ATTN_BLEND_WINDOW = 64
LINEAR_ATTN_ACTIVATION_LIMIT = 1e4
ROUTER_LOGIT_LIMIT = 80.0
ROUTER_Z_LOSS_LIMIT = 80.0
ROUTER_ENTROPY_FLOOR = 1e-6
DEFAULT_TEMPERATURE_ANNEAL_FACTOR = 0.99
DEFAULT_MIN_TEMPERATURE = 0.3
