#!/usr/bin/env python3
"""Audit public MoE class usage without assuming YAML is the only API surface."""

from __future__ import annotations

import ast
import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MOE_ROOT = ROOT / "ultralytics/nn/modules/moe"


@dataclass(frozen=True)
class Usage:
    name: str
    source: str
    yaml: bool
    exported: bool
    tested: bool
    referenced: bool

    @property
    def disposition(self) -> str:
        if self.yaml or self.tested:
            return "retain"
        if self.exported or self.referenced:
            return "freeze"
        return "archive-candidate"


def _read_searchable_files(paths: list[Path]) -> dict[Path, str]:
    contents = {}
    for path in paths:
        try:
            contents[path] = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
    return contents


def _contains_symbol(contents: dict[Path, str], name: str) -> bool:
    pattern = re.compile(rf"\b{re.escape(name)}\b")
    return any(pattern.search(text) is not None for text in contents.values())


def _exported_names() -> set[str]:
    tree = ast.parse((MOE_ROOT / "__init__.py").read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(isinstance(target, ast.Name) and target.id == "__all__" for target in node.targets):
            return {item.value for item in node.value.elts if isinstance(item, ast.Constant) and isinstance(item.value, str)}
    return set()


def audit_usage(root: Path = ROOT) -> list[Usage]:
    definitions: dict[str, str] = {}
    for path in sorted(MOE_ROOT.glob("*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for node in tree.body:
            if isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
                definitions[node.name] = f"{path.name}:{node.lineno}"

    exported = _exported_names()
    yaml_files = _read_searchable_files(
        list((root / "ultralytics/cfg").rglob("*.yaml")) + list((root / "ultralytics/cfg").rglob("*.yml"))
    )
    test_files = _read_searchable_files(list((root / "tests").rglob("*.py")))
    reference_files = _read_searchable_files([
        path
        for folder in ("ultralytics", "scripts", "examples", "docs", "wiki")
        if (root / folder).exists()
        for path in (root / folder).rglob("*")
        if path.is_file() and path.suffix in {".py", ".md", ".ipynb"} and MOE_ROOT not in path.parents
    ])
    return [
        Usage(
            name=name,
            source=source,
            yaml=_contains_symbol(yaml_files, name),
            exported=name in exported,
            tested=_contains_symbol(test_files, name),
            referenced=_contains_symbol(reference_files, name),
        )
        for name, source in sorted(definitions.items())
    ]


def render_markdown(rows: list[Usage]) -> str:
    counts = {status: sum(row.disposition == status for row in rows) for status in ("retain", "freeze", "archive-candidate")}
    lines = [
        "# MoE Class Usage Audit",
        "",
        "> Generated by `python scripts/audit_moe_usage.py`; deletion requires manual checkpoint/API review.",
        "",
        f"- Canonical public class definitions: {len(rows)}",
        f"- Retain: {counts['retain']}",
        f"- Freeze: {counts['freeze']}",
        f"- Archive candidates: {counts['archive-candidate']}",
        "",
        "| Class | Source | YAML | Exported | Tests | Other refs | Disposition |",
        "|---|---|---:|---:|---:|---:|---|",
    ]
    lines.extend(
        f"| `{row.name}` | `{row.source}` | {'yes' if row.yaml else 'no'} | "
        f"{'yes' if row.exported else 'no'} | {'yes' if row.tested else 'no'} | "
        f"{'yes' if row.referenced else 'no'} | **{row.disposition}** |"
        for row in rows
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    print(render_markdown(audit_usage()), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
